#!/usr/bin/env sh

# This script generates a SwissRets model in the 'swissrets-model.ts' file from a JSON schema using Quicktype.
# Please avoid manual modifications to 'swissrets-model.ts' and instead update the JSON schema,
# then run 'yarn generate-model' to reflect those changes in the generated TypeScript model.
model=src/ts/model/swissrets-model.ts
schema=schema/swissRetsSchema.json
reduced_schema=${schema}.reduced
printf "\
/* eslint-disable max-lines */
// This file was automatically generated by %s.\n\
// DO NOT MODIFY IT BY HAND.\n\
// Instead, modify the source %s,\n\
// and run %s to regenerate this file.\n\n\
" "$0" "$schema" "$0" > $model

node -pe "
  const json = require('./$schema');
  JSON.stringify(json);
" > $reduced_schema

yarn -s quicktype \
  --acronym-style camel \
  --just-types \
  --no-boolean-strings \
  --no-date-times \
  --no-integer-strings \
  -l typescript \
  -s schema $reduced_schema \
  -t SwissRetsInventory  >> $model

# rm $reduced_schema

# replace interface by classes, otherwise es6 won't end up with classes being exported
sed -i.bak 's/ interface / & /g' $model


unset model schema reduced_schema file_header
