name: Release

on:
  workflow_dispatch:
    inputs:
      semver:
        type: choice
        required: true
        default: patch
        options: [patch, minor, major]
        description: The semver of the release.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      checks: write
    steps:
      - name: Get releaser app token
        id: releaser-app-token
        uses: actions/create-github-app-token@a5be4722a6091c4e20293de271822a5532f23326
        with:
          app-id: ${{ secrets.RELEASER_APP_ID }}
          private-key: ${{ secrets.RELEASER_APP_KEY }}

      - uses: actions/checkout@v4
        with:
            token: ${{ steps.releaser-app-token.outputs.token }}
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@qualipool'

        ######
        ## Calculate next version based on user semver input
        ## Update version and create tag and push to main
        ######
      - name: Calculate next version based on semver input
        id: next_version
        uses: zwaldowski/semver-release-action@a6a8309186ccf60c52ea2463a723c78d3b924577 # v4
        with:
          preid: beta
          dry_run: true
          per_branch: true
          bump: ${{ github.event.inputs.semver }}
          github_token: ${{ github.token }}

      - name: Set git user and email
        uses: fregante/setup-git-user@024bc0b8e177d7e77203b48dab6fb45666854b35 # v2

      - name: Bump version in package.json
        uses: reedyuk/npm-version@15e0d016f632fe38bbb704910b8359f23262deb7 # 1.2.2
        with:
          version: ${{ steps.next_version.outputs.version }}

