name: publish
description: publish the npm package
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@qualipool'

      ######
      ## Build package and publish it to GitHub packages
      ######
      - name: Install dependencies
        run: npm ci
      - name: Verify the integrity of signatures for installed dependencies
        run: npm audit signatures
      - name: Build the package
        run: npm run build
      - name: Copy documentation to the dist folder
        run: mkdir dist/docs & cp -a docs/. dist/docs
      - name: Publish the package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
